In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()


In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))


tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.randn(4, 8))
Y.mean()

tensor(-1.4435e-08, grad_fn=<MeanBackward0>)

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.zeros(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)
    

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.5634, -0.1450, -0.4371],
        [ 0.2155, -0.2792,  2.4721],
        [ 0.2723,  0.0226,  0.9319],
        [-1.4027, -0.1179,  0.1315],
        [-2.2357, -1.2426,  0.4115]], requires_grad=True)

In [7]:
linear(torch.randn(2, 5))

tensor([[0.6135, 1.1203, 0.0000],
        [1.3036, 0.6715, 3.0004]])

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.randn(2, 64))


tensor([[ 5.4987],
        [15.6685]])